projectTitle: AbExp

vcf_input_dir: "example/clinvar_chr22"
# set this to True if you are sure that the variants are already normalized
# and contig names start with "chr"
vcf_is_normalized: False

output_dir: "example/output_hg38"
# output_dir: "example/output_hg19"

predict_abexp_models:
  - "abexp_v1.1"
#  - "abexp_v1.1_Enformer"
#  - "abexp_v1.1_nobcv"


human_genome_version: "hg38"
# human_genome_version: "hg19"

fasta_file: "example/chr22_hg38.fa"
# fasta_file: "example/chr22_hg19.fa"

# fasta file index is by default `fasta_file + ".fai"` but could be changed here:
# fasta_file_idx: "example/chr22_hg38.fa.fai"
# fasta_file_idx: "example/chr22_hg19.fa.fai"

gtf_file: "example/chr22.gencode.v40.annotation.gtf.gz"
# gtf_file: "example/chr22.gencode.v40lift37.annotation.gtf.gz"

# mapping of chromosome names. By default, maps them to "chr" prefix.
chrom_alias_tsv: "{SNAKEMAKE_DIR}/resources/chromAlias.tsv"