canonical_transcript_pq: "/s/project/rep/processed/training_results_v14/general/gtex_canonical_transcript.parquet"
subtissue_level_isoform_contribution_scores_pq: "/s/project/rep/processed/training_results_v14/general/gtex_subtissue_level_pext_scores.parquet"
expressed_genes_pq: "/s/project/rep/processed/training_results_v14/gtex_v8/gene_is_expressed_per_subtissue.parquet"
gtex_expected_expr: "/s/project/rep/processed/training_results_v14/gtex_v8/feature_sets/expected_expr.py/data.parquet"

vep:
  version: 108
  vep_bin: "vep"
  perl_bin: "perl"
  vep_cache_dir: "/s/raw/vep/{vep_version}"
  cadd_dir: "/s/raw/cadd/v1.6/{human_genome_assembly}"
  loftee_data_dir: "/s/raw/loftee/{human_genome_assembly}"
  loftee_src_path: "/s/raw/loftee/{human_genome_assembly}_src"

absplice:
  splicemap:
    psi3: '/s/project/abexp_veff/resources/absplice_splicemaps/splicemap_{genome}/{tissue}_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz'
    psi5: '/s/project/abexp_veff/resources/absplice_splicemaps/splicemap_{genome}/{tissue}_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz'
  use_spliceai_rocksdb: True
  spliceai_rocksdb_path: 
    hg19: '/s/project/abexp_veff/resources/spliceai_rocksdb/spliceAI_hg19_chr{chromosome}.db'
    hg38: '/s/project/abexp_veff/resources/spliceai_rocksdb/spliceAI_hg38_chr{chromosome}.db'

