boosting_type: gbdt
class_weight: null
colsample_bytree: 1.0
importance_type: split
learning_rate: 0.1
max_depth: -1
min_child_samples: 20
min_child_weight: 0.001
min_split_gain: 0.0
model_class: lightgbm.sklearn.LGBMRegressor
n_estimators: 100
n_jobs: 32
num_leaves: 31
objective: null
random_state: null
reg_alpha: 0.0
reg_lambda: 0.0
silent: warn
subsample: 1.0
subsample_for_bin: 200000
subsample_freq: 0
